"""Generate MATLAB scripts that adapt Simulink templates for the current design.

Instead of building SimPowerSystems models from scratch (which requires physical
port connections that can't be done using add_line), this module generates a
``build_model.m`` script that:

1. Copies the appropriate base template .slx to the run directory.
2. Loads it and updates component parameters (L, C, R_load, etc.) via set_param.
3. Saves it as ``acss_model.slx``.

This lets the AI adjust topology parameters while leveraging the existing
template's correct SimPowerSystems wiring.
"""

from __future__ import annotations

import logging
import math
import shutil
from pathlib import Path

from src.agents._topology_meta import power_stage_family
from src.contracts import ControlDesign, RequirementSpec, TopologyDesign

_log = logging.getLogger(__name__)

# Base templates per topology family.
_TEMPLATE_MAP: dict[str, str] = {
    'dc_dc_nonisolated': 'examples/topology.slx',
    'dc_dc_isolated': 'examples/topology_isolated.slx',
    'dc_dc_resonant': 'examples/topology_resonant.slx',
    'dc_ac_inverter': 'examples/topology_inverter.slx',
}


class SimulinkModelBuilder:
    """Generates a MATLAB script that adapts a Simulink template for the current design."""

    def __init__(
        self,
        topology: TopologyDesign,
        req: RequirementSpec,
        control: ControlDesign,
    ) -> None:
        self.topology = topology
        self.req = req
        self.control = control

    def generate_build_script(
        self,
        out_dir: Path,
        sfun_name: str = 'control_sfunc',
    ) -> Path:
        """Generate ``build_model.m`` and return its path."""
        fam = power_stage_family(self.topology.topology)
        code = self._build_adapt_m(fam, sfun_name)

        path = out_dir / 'build_model.m'
        path.write_text(code, encoding='utf-8')
        _log.info('Generated build_model.m for %s topology', self.topology.topology)
        return path

    def _build_adapt_m(self, fam: str, sfun_name: str) -> str:
        req = self.req
        top = self.topology
        ctrl = self.control

        vin = float(req.vin_nominal_v)
        l_h = float(top.inductor_uH) * 1e-6
        c_f = float(top.capacitor_uF) * 1e-6
        r_load = float(req.vout_target_v) ** 2 / max(float(req.pout_w), 1e-9)
        i_load = float(req.vout_target_v) / max(r_load, 1e-9)

        r_l = max(0.0005, 0.001 * math.sqrt(max(l_h, 1e-6) / 1e-4) / max(math.sqrt(i_load / 10.0), 0.1))
        r_c = max(0.0002, 0.0005 * math.sqrt(max(c_f, 1e-6) / 1e-4) / max(math.sqrt(i_load / 10.0), 0.1))

        tstop = max(0.02, float(req.settling_time_ms_max) * 1e-3 * 5.0)
        ts = float(ctrl.sample_time_s)

        # Find the base template path — use absolute path so MATLAB can find it
        # regardless of the working directory (important for MCP backend).
        template_rel = _TEMPLATE_MAP.get(fam, 'examples/topology.slx')
        project_root = Path(__file__).resolve().parent.parent
        template_abs = (project_root / template_rel).resolve().as_posix()

        # Build MATLAB code using string concatenation to avoid f-string escaping issues.
        lines = [
            'function build_model()',
            f'% Auto-generated by ACSS model_builder — adapts a Simulink template for {top.topology}.',
            '% Copies the base template, updates component parameters, saves as acss_model.slx.',
            '',
            "modelName = 'acss_model';",
            f"templatePath = '{template_abs}';",
            '',
            "if ~isfile(templatePath)",
            "    error('Template not found: %s', templatePath);",
            'end',
            '',
            '% Copy template to run directory as acss_model.slx.',
            "dstPath = fullfile(pwd, [modelName '.slx']);",
            'copyfile(templatePath, dstPath);',
            '',
            '% Load the copied model.',
            'load_system(dstPath);',
            '',
            '% Update component parameters where they exist.',
            'params = struct();',
            f"params.L = '{l_h:.12g}';",
            f"params.Lf = '{l_h:.12g}';",
            f"params.C = '{c_f:.12g}';",
            f"params.Cf = '{c_f:.12g}';",
            f"params.R_load = '{r_load:.12g}';",
            f"params.R_L = '{r_l:.12g}';",
            f"params.R_C = '{r_c:.12g}';",
            f"params.V_source = '{vin}';",
            f"params.Vin_nom = '{vin}';",
            f"params.Vdc = '{vin}';",
            f"params.N = '{top.turns_ratio:.12g}';",
            f"params.n = '{top.turns_ratio:.12g}';",
            '',
            '% Apply parameters to all blocks that reference par.* fields.',
            "blocks = find_system(modelName, 'Type', 'block');",
            'for i = 1:numel(blocks)',
            '    blk = blocks{i};',
            '    try',
            "        maskVars = get_param(blk, 'MaskVariables');",
            '        if isempty(maskVars), continue; end',
            "        maskVals = get_param(blk, 'MaskValues');",
            "        maskNames = get_param(blk, 'MaskNames');",
            '        changed = false;',
            '        for j = 1:numel(maskNames)',
            '            name = maskNames{j};',
            '            if isfield(params, name)',
            '                maskVals{j} = params.(name);',
            '                changed = true;',
            '            end',
            '        end',
            '        if changed',
            "            set_param(blk, 'MaskValues', maskVals);",
            '        end',
            '    catch',
            '    end',
            'end',
            '',
            '% Update solver settings.',
            "set_param(modelName, ...",
            "    'Solver', 'ode23tb', ...",
            f"    'StopTime', '{tstop:.12g}', ...",
            f"    'MaxStep', '{ts:.12g}', ...",
            "    'RelTol', '1e-4', ...",
            "    'AbsTol', '1e-6');",
            '',
            '% Save the modified model.',
            'save_system(modelName, dstPath);',
            "fprintf('[ACSS] Model adapted: %s\\n', dstPath);",
            'end',
        ]
        return '\n'.join(lines) + '\n'
